const gymsharkProducts = [
    {
        id: 1,
        name: 'GFX-Crew-Socks-3pk',
        productName: 'GFX Crew Socks',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/3pk1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/3pk2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/3pk3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/3pk4.JPG?raw=true',
        color: 'White',
        category: 'Body fit',
        size: 'S',
        price: 270,
        type: ' c/u ',
    },
    {
        id: 111,
        name: 'Crew-Socks-7PK',
        productName: 'Crew socks',
        image1: 'https://cdn.shopify.com/s/files/1/0156/6146/files/GFXCrewSocks7PKGSWhiteI3A2V-WB57-0081-4_1920x.jpg?v=1695813528',
        image2: 'https://cdn.shopify.com/s/files/1/0156/6146/files/GFXCrewSocks7PKGSWhiteI3A2V-WB57-0151_828x.jpg?v=1695813529',
        color: 'White',
        category: 'Body fit',
        size: 'M',
        price: 320,
        type: ' c/u '
    },
    {
        id: 2,
        name: 'Crew-Socks-5pk',
        productName: 'Crew socks',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/5pk1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/5pk2.JPG?raw=true',
        color: 'Plum Pink/Deep Teal/Citrus Green/Capri Blue/Grape Purple',
        category: 'Body fit',
        size: 'S',
        price: 250,
        type: ' c/u '

    },
    {
        id: 222,
        name: 'calcetines-gymshark',
        productName: 'Calcetines gymshark',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/calcetinesgymshark3.jpeg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/calcetinesgymshark4.jpeg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/calcetinesgymshark2.jpeg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/calcetinesgymshark1.jpeg?raw=true',
        color:  'White',
        category: 'Body fit',
        size: 'S | M | L',
        price: 250,
        type: ' c/u ',
        stock: '',

    },
    {
        id: 434,
        name: 'Calcetines-GYMSHARK-Pastel',
        productName: 'Calcetines GYMSHARK',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/CalcetinesGYMSHARKPastel2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/CalcetinesGYMSHARKPastel1.JPG?raw=true',
        color:  'Blanco| Rosa | Gris',
        category: 'Body fit',
        size: 'S M L',
        price: 390,
        type: '1100 Pack completo',

    },
    {
        id: 3,
        name: 'Adapt-Animal-Seamless-Crop-Tank',
        productName: 'Adapt Animal Seamless Crop Tank',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/cherrybrown1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/cherrybrown2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/cherrybrown3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/cherrybrown4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/cherrybrown5.JPG?raw=true',
        color: 'Reef | Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 1190
    },
    {
        id: 4,
        name: 'Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greenbra6.JPG?raw=true',
        color: 'Desert Sage Green',
        category: 'Body fit',
        size: 'S',
        price: 990
    },
    {
        id: 5,
        name: 'Adapt-Camo-Seamless-Sports-Bra',
        productName: 'Adapt Camo Seamless Sports Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/greybra6.JPG?raw=true',
        color: 'Pebble Grey/Soul Brown',
        category: 'Body fit',
        size: 'M',
        price: 1090,
    },
    {
        id: 6,
        name: 'Adapt-Camo-Seamless-Lace-Up-Back-Top',
        productName: 'Adapt Camo Seamless Lace Up Back Top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/redback6.JPG?raw=true',
        color: 'Storm Red/Cherry Brown',
        category: 'Body fit',
        size: 'S',
        price: 1190,
    },
    {
        id: 7,
        name: 'Crossover-Sport-Bra',
        productName: 'Crossover Sport Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/lavenderbra6.JPG?raw=true',
        color: 'Slate Lavender',
        category: 'Body fit',
        size: 'M | S',
        price: 990
    },
    {
        id: 8,
        name: 'Elevate-Longline-Sports-Bra',
        productName: 'Elevate Longline Sports Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/olivebra6.JPG?raw=true',
        color: 'Moss Olive',
        category: 'Body fit',
        size: 'S | M',
        price: 1090
    },
    {
        id: 9,
        name: 'Legacy-Ruched-Tights-Shorts',
        productName: 'Legacy Ruched Tights Shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/bluelegacy6.JPG?raw=true',
        color: 'Lakgeside Blue',
        category: 'Body fit',
        size: 'S',
        price: 1190
    },
    {
        id: 99,
        name: 'Legacy-Shorts-Washed-Green',
        productName: 'Legacy Shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legacyshort1.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legacyshort2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legacyshort3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legacyshort4.jpg?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legacyshort5.jpg?raw=true',
        color: 'Washed Green',
        category: 'Body fit',
        size: 'M',
        price: 1190,
        stock: 'Agotado',
    },
    {
        id: 10,
        name: 'Pocket-Shorts',
        productName: 'Pocket Shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue3.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue4.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue5.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue6.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/pocketblue1.JPG?raw=true',
        color: 'Denim Blue',
        category: 'Body fit',
        size: 'M',
        price: 1090
    },
    {
        name: 'Studio-Shorts',
        productName: 'Studio Shorts',
        image1: 'https://cdn.shopify.com/s/files/1/1367/5207/products/StudioWShortsBlack-B1A9N-BBBB.A_1920x.jpg?v=1656931461',
        image2: 'https://cdn.shopify.com/s/files/1/1367/5207/products/StudioWShortsBlack-B1A9N-BBBB.D2_384x.jpg?v=1656931461',
        image3: 'https://cdn.shopify.com/s/files/1/1367/5207/products/StudioWShortsBlack-B1A9N-BBBB.D3_384x.jpg?v=1656931461',
        color: 'Black',
        category: 'Body fit',
        size: 'S',
        price: 990
    },
    {
        id: 12,
        name: 'Gs-Power-Original-Leggings',
        productName: 'Gs Power Original Leggings',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/powerblue6.JPG?raw=true',
        color: 'Coastal Blue',
        category: 'Body fit',
        size: 'S',
        price: 1390
    },
    {
        id: 13,
        name: 'Adapt-Animal-Seamless-Leggings',
        productName: 'Adapt Animal Seamless Leggins',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack6.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/legingblack7.JPG?raw=true',
        color: 'Reef | Black',
        category: 'Body fit',
        size: 'S',
        price: 1490,
        stock: 'Agotado',
    },
    {
        id: 14,
        name: 'Flex-High-Waisted-Leggings',
        productName: 'Flex High Waisted Leggings',
        image1: 'https://cdn.shopify.com/s/files/1/1367/5207/products/FlexHwLeggingsEarlBlueMarlB1A2Q.A_ZH_ZH_d9ffee9e-5a61-4222-8c99-5007c686e0c9_1920x.jpg?v=1652186862',
        image2: 'https://cdn.shopify.com/s/files/1/1367/5207/products/FlexHwLeggingsEarlBlueMarlB1A2Q.D2_ZH_ZH_8b57f430-3480-4a82-9c91-1d7008cf9a8c_384x.jpg?v=1652186862',
        image3: 'https://cdn.shopify.com/s/files/1/1367/5207/products/FlexHwLeggingsEarlBlueMarlB1A2Q.D3_ZH_ZH_2ee97bd0-00af-4d98-a8bd-49c446c7130e_384x.jpg?v=1652186862',
        color: 'Earl Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 1390,
        stock: 'Agotado',
    },
    {
        id: 15,
        name: 'Legacy-Sports-Bra',
        productName: 'Legacy Sports Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/hoyabra6.JPG?raw=true',
        color: 'Hoya Green',
        category: 'Body fit',
        size: 'S',
        price: 990
    },
    {
        id: 16,
        name: 'Vital-Seamless-2.0-High-Neck-Midi_top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblack1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblack2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblack3.JPG?raw=true',
        color: 'Black Marl',
        category: 'Body fit',
        size: 'M',
        price: 1290
    },
    {
        id: 17,
        name: 'Vital-Seamless-2.0-High-Neck-Midi-top',
        productName: 'Vital Seamless 2.0 High Neck Midi top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/gymsharkImages/midtopblue6.JPG?raw=true',
        color: 'Stellar Blue Marl',
        category: 'Body fit',
        size: 'S',
        price: 1190
    }
]

export default gymsharkProducts;
