const wproducts = [
    {
        id: 1,
        name: 'Falda-Deportiva-Basic-tenis',
        productName: 'Falda Deportiva Básica De Tenis',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/faldatenis4.jpg?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'S | M',
        price: 490,
        stock: 'Agotado',
    },
    {
        id: 2,
        name: 'Gym-Sport-Bra',
        productName: 'Gym Sport Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra3.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra2.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymbra5.JPG?raw=true',
        color: 'Negro, Beige Blanco',
        category: 'Body fit',
        size: 'S',
        price: 360,
        stock: 'Agotado',
    },
    {
        id: 3,
        name: 'Gym-Shorts',
        productName: 'Gym shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort1.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/gymshort4.JPG?raw=true',
        color: 'Negro, Morado Claro, Morado Oscuro',
        category: 'Body fit',
        size: 'S | M',
        price: 395,
        stock: 'Negro Agotado',
    },
    {
        id: 4,
        name: 'Gym-Shorts-Highs',
        productName: 'Gym Shorts Highs',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/shorthigh1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/shorthigh2.JPG?raw=true',
        color: 'Negro, Gris, Beige, Celeste Claro',
        category: 'Body fit',
        size: 'S',
        price: 395,
        stock: 'Negro Agotado'
    },
    {
        id: 5,
        name: 'Biker-Shorts',
        productName: 'Biker Shorts',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort4.jpg?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/bykershort5.JPG?raw=true',
        color: 'Negro, Gris Claro, Naranja, Gris Oscuro',
        category: 'Body fit',
        size: 's',
        price: 430,
        stock: 'Agotado Negro Gris Naranja',
    },
    {
        id: 6,
        name: 'Seamless-Crop-Top',
        productName: 'Seamless Crop Top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop1.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop2.jpg?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop3.jpg?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/croptop4.jpg?raw=true',
        color: 'Negro, Morado, Rosado, Gris',
        category: 'Body fit',
        size: 'S',
        price: 380,
        stock: 'Negro y rosado agotado',
    },
    {
        id: 7,
        name: 'Set-completo',
        productName: 'Set completo',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/setcompleto1.JPG?raw=true',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/setcompleto2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/setcompleto3.JPG?raw=true',
        color: 'Verde claro',
        category: 'Body fit',
        size: 'XS | S',
        price: 890,
        stock: '',
    },
    {
        id: 8,
        name: 'Seamles-Crop-tops',
        productName: 'Seamless crop top',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/seamlescroptops.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/seamlescroptops3.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/seamlescroptops2.JPG?raw=true',
        color: 'Negro|verde|rosa|gris',
        category: 'Body fit',
        size: 'M',
        price: 380,
        stock: '',
    },
    {
        id: 9,
        name: 'Jumpsuit',
        productName: 'Jumpsuit',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Jumpsuit1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Jumpsuit2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Jumpsuit3.JPG?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'S | M',
        price: 850,
        stock: 'Agotado',
    },
    {
        id: 10,
        name: 'Tennis-Basic-1',
        productName: 'Tennis Bassic',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Tennisbasic1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Tennisbasic2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Tennisbasic3.JPG?raw=true',
        color: 'Rosado',
        category: 'Body fit',
        size: 'S | M',
        price: 495,
        stock: '',
    },
    {
        id: 11,
        name: 'Tennis-Basic-2',
        productName: 'Tennis Bassic',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Tennisbasic2-1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Tennisbasic%202-2.JPG?raw=true',
        color: 'Morado',
        category: 'Body fit',
        size: 'S | M',
        price: 520,
        stock: 'talla M agotada',
    },
    {
        id: 12,
        name: 'Gym-shorts-levanta-glúteo',
        productName: 'Gym shorts levanta glúteo',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Gymshortslevantagl%C3%BAteo2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Gymshortslevantagl%C3%BAteo1.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Gymshortslevantagl%C3%BAteo3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Gymshortslevantagl%C3%BAteo3.JPG?raw=true',
        color: 'Negro verde rosa gris',
        category: 'Body fit',
        size: 'M',
        price: 395,
        stock: '',
    },
    {
        id: 13,
        name: 'Sujetador-deportivo-1',
        productName: 'Sujetador deportivo',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo1.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Sujetadordeportivo6.JPG?raw=true',
        color: 'Negro | Blanco',
        category: 'Body fit',
        size: 'M',
        price: 330,
        stock: '',
    },
    {
        id: 14,
        name: 'Mini-llavero',
        productName: 'Mini llavero',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/minillavero1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/minillavero2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/minillavero3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/minillavero4.JPG?raw=true',
        color: 'Negro',
        category: 'Accesorio',
        size: 'small',
        price: 250,
        stock: '',
    },
    {
        id: 15,
        name: 'Camisa-Oversize-1',
        productName: 'Camisa Oversize',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/camisaoversize1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/camisaoversize2.JPG?raw=true',
        color: 'Blanco',
        category: 'Prenda',
        size: 'M',
        price: 450,
        stock: 'agotado',
    },
    {
        id: 16,
        name: 'Camisa-Oversize-2',
        productName: 'Camisa Oversize',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Camisaoversize2-1.JPG?raw=true',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Camisaoversize2-2.JPG?raw=true',
        color: 'Negro',
        category: 'Prenda',
        size: 'M',
        price: 450,
        stock: '',
    },
    {   
        id: 17,
        name: 'Bandita-para-el-cabello',
        productName: 'Banditas para el cabello',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello2.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello3.JPG?raw=true',
        image4: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello4.JPG?raw=true',
        image5: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello5.JPG?raw=true',
        image6: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/banditasparaelcabello6.JPG?raw=true',
        color: 'Negro|Cafe|Blanco|Rosado|',
        category: 'Accesorios',
        size: 'M',
        price: 30,
        stock: 'Agotado',
    }, 
    {   
        id: 18,
        name: 'Tennis-Basic-Black-White',
        productName: 'Tennis Bassic',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/TennisbasicBlack_White1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/TennisbasicBlack_White2.JPG?raw=true',
        color: 'Blanco|Negro',
        category: 'Prenda',
        size: 'M',
        price: 595,
    },
    {   
        id: 19,
        name: 'Set-Completo-Akatsuki',
        productName: 'Set Completo Akatsuki',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/SetcompletoAkatsuki.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/SetcompletoAkatsuki.JPG?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'M',
        price: 1695,
    },
    {   
        id: 20,
        name: 'Set-Completo-Brown',
        productName: 'Set Completo Cafe',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Setcompletobrown3.jpg?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Setcompletobrown2.jpg?raw=true',
        color: 'Cafe',
        category: 'Body fit',
        size: 'M',
        price: 1695,
    },
    {   
        id: 21,
        name: 'Set-Completo-Black',
        productName: 'Set Completo Negro',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Setcompletoblack2.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Setcompletoblack1.JPG?raw=true',
        image3: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Setcompletoblack1.JPG?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'S | M',
        price: 1695,
        stock: 'Agotado',
    },
    {   
        id: 22,
        name: 'Set-Completo-Black-Wolves',
        productName: 'Sports Bra',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/SportsBraWolve1.JPG?raw=true',
        image2: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/SportsBraWolve2.JPG?raw=true',
        color: 'Negro',
        category: 'Body fit',
        size: 'M',
        price: 875,
    },
    {   
        id: 23,
        name: 'Celsius-On-The-Go-Berry',
        productName: 'Celsisu On the Go Berry',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Celsius%20On-The-Go1.JPG?raw=true',
        image2: 'https://m.media-amazon.com/images/I/817S691c6UL._AC_SX679_.jpg',
        size: '14',
        price: 690,
    },
    {   
        id: 24,
        name: 'Celsius-On-The-Go-Kiwi',
        productName: 'Celsisu On the Go Kiwi',
        image1: 'https://github.com/Jose-Vargas-Guerrero/gymlandImages/blob/main/shein/Celsius%20On-The-Go2.JPG?raw=true',
        image2: 'https://m.media-amazon.com/images/I/81tlC7mQl6L._AC_SX679_.jpg',
        size: '14',
        price: 690,
    }, 

];  

export default wproducts;
